### PR TITLE
Add osx build.

### PR DESCRIPTION
**Pull request by 183amir**

### CODE REVIEW

**Comment by 183amir** [comment]
Hey @conda-forge/core why this feedstock has appvoyer while the build is being skipped with windows?

**Comment by pelson** [comment]
Did you run `conda smithy rerender`? Normally that will create an `appveyor_disabled.yml` (or similar such name) - the AppVeyor setup is configured to skip the build if it doesn't have an `appveyor.yml` (this feedstock doesn't have an appveyor.yml).

Is the question, why does the README show the AppVeyor badge?

**Comment by 183amir** [comment]
No the question is why does appvoyer runs against this PR: https://ci.appveyor.com/project/conda-forge/bob-ip-color-feedstock/build/1.0.8

**Comment by pelson** [comment]
I see no builds when I look at https://ci.appveyor.com/project/conda-forge/bob-ip-color-feedstock.
Are you certain there are actually builds, and not just the fact that `appveyor` _knows_ about this repo?

**Comment by 183amir** [comment]
can I do something so that `appveyor` _forgets_ this repo?

**Comment by pelson** [comment]
> can I do something so that appveyor forgets this repo?

No, there is no need. _All_ feedstocks are registered with AppVeyor, but only the ones that need it actually _run_ an appveyor script. Because this feedstock defines the fact that there is no Windows build, this feedstock is one of those which doesn't run anything on AppVeyor (hence me not seeing any builds in my previous comment).

Is there something that is driving the request? (I'm trying to understand the motivation so that I can give you a better answer / maybe fix a different problem)

**Comment by 183amir** [comment]
tmp_31898-screenshot_20160517-083652 2-1494772551
The problem is I got 4 checks for this pul request. And the check for appveyor shows as failed while this does not need to be checked against appveyor.

**Comment by pelson** [comment]
Interesting. I agree, this shouldn't be doing that. FWIW, that does _not_ happen for any of the other feedstocks I have seen. Even more bizarrely, it also links to an AppVeyor build which doesn't exist. All in all, this is very peculiar.

I have just taken a look at the registered webhooks on this repo, and it appears they have each been duplicated. I imagine this is a result of re-registering with staged-recipes, or some other such peculiarity. I have removed those duplicates, and hope that may resolve the issue. If not, we can just remove the AppVeyor hook completely for this feedstock.

**Pull request merged**
